---
- name: 
  hosts: all
  become: true
  vars:
    docker_users:
      - panda
      - vagrand
  roles:
    - user
    - packages
    - geerlingguy.docker
    - christiangda.awscli
    - christiangda.awscli_configure
    - diodonfrost.terraform